apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settings
  template:
    metadata:
      labels:
        app: settings
    spec:
      serviceAccountName: KUSTOMIZE_SVC_ACCOUNT_NAME
      automountServiceAccountToken: true
      containers:
        - name: settings
          image: KUSTOMIZE_IMAGE
          ports:
            - containerPort: 5006
              name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: settings-service
spec:
  selector:
    app: settings
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5006
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: settings-service-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: KUSTOMIZE_API_HOST
      http:
        paths:
          - path: /KUSTOMIZE_TENANT/settings
            backend:
              service:
                name: settings-service
                port:
                  number: 80
            pathType: Prefix
